# Base environment for LLM deployment
# Adjust dependencies based on your specific model requirements

name: llm-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - azure-ai-ml>=1.12.0
    - azureml-defaults
    - torch>=2.1.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    # Model-specific dependencies (uncomment if needed)
    - einops
    - sentencepiece
    - tiktoken
    - protobuf